server:
  port: 8089

#logging:
#  level:
#    org.springframework: DEBUG

spring:
  messages:
    basename: messages
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    user:
      name: joonsoung93
      password: wnstjd93!

management:
  endpoints:
    web:
      exposure:
        include: "*"




